Documentation and Refactoring
nm-wu/ordo pull request #3
Opened 2021-10-15 16:06 UTC by MacOS

This pull request aims at improving the code quality, which is achieved by

1. adding preliminary  documentation, and 
2. refactoring the code with respect to code quality, e.g. indentation and deletion of unnecessary variables declarations.

2021-10-19 21:50 UTC, mrcalvin requested changes

2021-10-19 21:50 UTC, mrcalvin commented on ordo/ordo.js
> +<<<<<<< HEAD
Pls remove the merge artifacts, first!

2021-10-19 21:50 UTC, mrcalvin commented on ordo/ordo.js
> +=======
Pls remove the merge artifacts, first!

2021-10-19 21:50 UTC, mrcalvin commented on ordo/ordo.js
> +>>>>>>> 0c1a4b94feb516d3f1f0a5e4f8cda3e37fe3e17f
Pls remove the merge artifacts, first!

2021-10-19 21:50 UTC, mrcalvin commented on ordo/ordo.js
> +     * Toggels the admonition div between the states open and close
Toggels -> Toggles?

2021-10-19 21:50 UTC, mrcalvin commented on ordo/ordo.js
> +<<<<<<< HEAD
Pls. remove the merge artifacts first.

2021-10-19 21:50 UTC, mrcalvin commented on ordo/ordo.js
> +=======
Pls. remove the merge artifacts first.

2021-10-19 21:50 UTC, mrcalvin commented on ordo/ordo.js
> +>>>>>>> 0c1a4b94feb516d3f1f0a5e4f8cda3e37fe3e17f
Pls. remove the merge artifacts first.

2021-10-19 21:50 UTC, mrcalvin commented on ordo/ordo.js
> +<<<<<<< HEAD
Pls. remove the merge artifacts first.

2021-10-19 21:50 UTC, mrcalvin commented on ordo/ordo.js
> +=======
Pls. remove the merge artifacts first.

2021-10-19 21:50 UTC, mrcalvin commented on ordo/ordo.js
> +>>>>>>> 0c1a4b94feb516d3f1f0a5e4f8cda3e37fe3e17f
Pls. remove the merge artifacts first.

2021-10-19 21:50 UTC, mrcalvin commented on ordo/ordo.js
> +<<<<<<< HEAD
Pls. remove the merge artifacts first.

2021-10-19 21:50 UTC, mrcalvin commented on ordo/ordo.js
> +=======
Pls. remove the merge artifacts first.

2021-10-19 21:50 UTC, mrcalvin commented on ordo/ordo.js
> +>>>>>>> 0c1a4b94feb516d3f1f0a5e4f8cda3e37fe3e17f
Pls. remove the merge artifacts first.

2021-10-19 21:50 UTC, mrcalvin commented on ordo/ordo.js
> +<<<<<<< HEAD
Pls. remove the merge artifacts first.

2021-10-19 21:50 UTC, mrcalvin commented on ordo/ordo.js
> +=======
Pls. remove the merge artifacts first.

2021-10-19 21:50 UTC, mrcalvin commented on ordo/ordo.js
> +>>>>>>> 0c1a4b94feb516d3f1f0a5e4f8cda3e37fe3e17f
Pls. remove the merge artifacts first.

2021-10-19 21:50 UTC, mrcalvin commented on ordo/ordo.js
> +=======
Pls. remove the merge artifacts first.

2021-10-19 21:50 UTC, mrcalvin commented on ordo/ordo.js
> +>>>>>>> 0c1a4b94feb516d3f1f0a5e4f8cda3e37fe3e17f
Pls. remove the merge artifacts first.

2021-10-20 07:11 UTC, MacOS commented on ordo/ordo.js
> +<<<<<<< HEAD
done

2021-10-20 07:11 UTC, MacOS commented on ordo/ordo.js
> +=======
done

2021-10-20 07:11 UTC, MacOS commented on ordo/ordo.js
> +>>>>>>> 0c1a4b94feb516d3f1f0a5e4f8cda3e37fe3e17f
done

2021-10-20 07:13 UTC, MacOS commented on ordo/ordo.js
> +     * Toggels the admonition div between the states open and close
done

2021-10-20 07:13 UTC, MacOS commented on ordo/ordo.js
> +<<<<<<< HEAD
done

2021-10-20 07:15 UTC, MacOS commented on ordo/ordo.js
> +=======
done.

2021-10-20 07:16 UTC, MacOS commented on ordo/ordo.js
> +>>>>>>> 0c1a4b94feb516d3f1f0a5e4f8cda3e37fe3e17f
done.

2021-10-20 07:16 UTC, MacOS commented on ordo/ordo.js
> +=======
done.

2021-10-20 07:16 UTC, MacOS commented on ordo/ordo.js
> +>>>>>>> 0c1a4b94feb516d3f1f0a5e4f8cda3e37fe3e17f
done.

2021-10-20 07:23 UTC, MacOS commented
I think the pull request has still an issue because the [defering mechanisms](https://github.com/nm-wu/ordo/blob/0c1a4b94feb516d3f1f0a5e4f8cda3e37fe3e17f/ordo/ordo.js#L286) in [initialilzeCells](https://github.com/nm-wu/ordo/blob/0c1a4b94feb516d3f1f0a5e4f8cda3e37fe3e17f/ordo/ordo.js#L277) is gone. In fact, I think that the function can be made simpler by deleting [the first loop](https://github.com/nm-wu/ordo/blob/0c1a4b94feb516d3f1f0a5e4f8cda3e37fe3e17f/ordo/ordo.js#L279) and only using [the event](https://github.com/nm-wu/ordo/blob/0c1a4b94feb516d3f1f0a5e4f8cda3e37fe3e17f/ordo/ordo.js#L286) as they do the same. But fixing this might be for the next pull request.

2025-02-03 19:30 UTC, closed without merging